import type { ListingCardData } from "../primitives/listing-card";
import type { ListingDetail } from "@/lib/services/web/listings";

/**
 * Curated development & fallback catalogue for Sunland Real Estates properties.
 * Provides rich high-resolution imagery, realistic Kenyan luxury pricing,
 * full specifications, and multi-category representation.
 */
export const MOCK_PROPERTIES: (ListingDetail & { category: "apartments" | "villas" | "commercial" | "land"; listingType: "for-rent" | "for-sale" })[] = [
  // ── Apartments ──
  {
    id: "prop-apt-01",
    slug: "luxury-3-bedroom-duplex-penthouse-lavington",
    title: "Luxury 3 Bedroom Duplex Penthouse, Lavington",
    location: "Lavington, Nairobi",
    status: "available",
    isFeatured: true,
    category: "apartments",
    listingType: "for-rent",
    priceKes: 180000,
    priceSuffix: "/ mo",
    imageUrl: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80",
    imageAlt: "Luxury 3 Bedroom Duplex Penthouse in Lavington",
    bedrooms: 3,
    bathrooms: 3,
    area: "250 m²",
    parkingSpaces: 2,
    propertyType: "Apartment",
    reference: "SL-LAV-001",
    description: "An exceptional modern duplex penthouse featuring panoramic city views, high ceilings, Italian fitted kitchen, and expansive private terrace in prime Lavington.",
    amenities: ["Swimming Pool", "High-Speed Elevators", "Backup Generator", "Borehole Water", "24/7 Manned Security", "Gym & Fitness Studio", "Solar Water Heating"],
    yearBuilt: 2023,
    images: [
      { url: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80", alt: "Living Area" },
      { url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80", alt: "Kitchen" },
      { url: "https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=1200&q=80", alt: "Master Suite" },
    ],
  },
  {
    id: "prop-apt-02",
    slug: "executive-2-bedroom-furnished-kileleshwa",
    title: "Executive 2 Bedroom Furnished Residence, Kileleshwa",
    location: "Kileleshwa, Nairobi",
    status: "available",
    isFeatured: false,
    category: "apartments",
    listingType: "for-rent",
    priceKes: 140000,
    priceSuffix: "/ mo",
    imageUrl: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80",
    imageAlt: "Executive Furnished Residence in Kileleshwa",
    bedrooms: 2,
    bathrooms: 2,
    area: "140 m²",
    parkingSpaces: 2,
    propertyType: "Apartment",
    reference: "SL-KIL-002",
    description: "Tastefully fully-furnished 2 bedroom ensuite apartment with bespoke Nordic interior finishes, open-plan kitchen, and lush leafy neighborhood views.",
    amenities: ["Fully Furnished", "High-Speed Internet", "Heated Swimming Pool", "CCTV Surveillance", "Concierge Reception"],
    yearBuilt: 2022,
    images: [
      { url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80", alt: "Interior" },
      { url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80", alt: "Bedroom" },
    ],
  },
  {
    id: "prop-apt-03",
    slug: "contemporary-3-bedroom-garden-apartment-kilimani",
    title: "Contemporary 3 Bedroom Garden Apartment, Kilimani",
    location: "Kilimani, Nairobi",
    status: "under_offer",
    isFeatured: false,
    category: "apartments",
    listingType: "for-rent",
    priceKes: 110000,
    priceSuffix: "/ mo",
    imageUrl: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80",
    imageAlt: "Contemporary Garden Apartment in Kilimani",
    bedrooms: 3,
    bathrooms: 2,
    area: "190 m²",
    parkingSpaces: 2,
    propertyType: "Apartment",
    reference: "SL-KIL-003",
    description: "Spacious ground-floor unit opening out to private landscaped gardens. Ideal for families seeking serenity within central Kilimani.",
    amenities: ["Private Garden", "Kids Play Area", "Borehole", "Full Power Backup"],
    yearBuilt: 2021,
    images: [
      { url: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80", alt: "Garden view" },
    ],
  },
  {
    id: "prop-apt-04",
    slug: "ultra-modern-studio-westlands",
    title: "Ultra-Modern Studio Suite, Westlands",
    location: "Westlands, Nairobi",
    status: "available",
    isFeatured: false,
    category: "apartments",
    listingType: "for-rent",
    priceKes: 65000,
    priceSuffix: "/ mo",
    imageUrl: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80",
    imageAlt: "Ultra-Modern Studio in Westlands",
    bedrooms: 1,
    bathrooms: 1,
    area: "65 m²",
    parkingSpaces: 1,
    propertyType: "Studio",
    reference: "SL-WST-004",
    description: "Compact luxury studio located walking distance from prime Westlands business and dining hubs. Rooftop lounge and sky gym.",
    amenities: ["Rooftop Infinity Pool", "Sky Lounge", "Meeting Rooms", "Concierge"],
    yearBuilt: 2024,
    images: [
      { url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80", alt: "Studio space" },
    ],
  },
  {
    id: "prop-apt-05",
    slug: "4-bedroom-penthouse-suite-riverside",
    title: "4 Bedroom Penthouse Suite, Riverside Drive",
    location: "Riverside, Nairobi",
    status: "available",
    isFeatured: true,
    category: "apartments",
    listingType: "for-sale",
    priceKes: 52000000,
    priceSuffix: null,
    imageUrl: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80",
    imageAlt: "Penthouse Suite in Riverside Drive",
    bedrooms: 4,
    bathrooms: 4,
    area: "380 m²",
    parkingSpaces: 3,
    propertyType: "Penthouse",
    reference: "SL-RIV-005",
    description: "An architectural tour-de-force with double-volume ceilings, wrap-around terraces, smart home automation, and private plunge pool.",
    amenities: ["Smart Home Automation", "Private Plunge Pool", "Clubhouse", "Electric Vehicle Charging"],
    yearBuilt: 2023,
    images: [
      { url: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80", alt: "Penthouse" },
    ],
  },

  // ── Villas & Houses ──
  {
    id: "prop-vil-01",
    slug: "contemporary-5-bedroom-villa-karen",
    title: "Contemporary 5 Bedroom Ambassadorial Villa, Karen",
    location: "Karen, Nairobi",
    status: "available",
    isFeatured: true,
    category: "villas",
    listingType: "for-sale",
    priceKes: 145000000,
    priceSuffix: null,
    imageUrl: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1200&q=80",
    imageAlt: "Contemporary Villa in Karen",
    bedrooms: 5,
    bathrooms: 5,
    area: "0.75 acres",
    parkingSpaces: 6,
    propertyType: "Villa",
    reference: "SL-KAR-101",
    description: "Stunning modern villa sitting on 0.75 acres of mature lush garden. Features infinity pool, floor-to-ceiling glass architecture, and detached staff quarters.",
    amenities: ["Infinity Pool", "Mature Garden", "Detached DSQ (2 Units)", "Perimeter Electric Fence", "Solar Backup", "Wine Cellar"],
    yearBuilt: 2023,
    images: [
      { url: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1200&q=80", alt: "Exterior Dusk" },
      { url: "https://images.unsplash.com/photo-1600585155282-35804ef0528e?auto=format&fit=crop&w=1200&q=80", alt: "Lounge" },
    ],
  },
  {
    id: "prop-vil-02",
    slug: "four-bedroom-luxury-villa-spring-valley",
    title: "Four Bedroom Luxury Villa, Spring Valley",
    location: "Spring Valley, Nairobi",
    status: "available",
    isFeatured: true,
    category: "villas",
    listingType: "for-sale",
    priceKes: 117500000,
    priceSuffix: null,
    imageUrl: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80",
    imageAlt: "Luxury Villa in Spring Valley",
    bedrooms: 4,
    bathrooms: 4,
    area: "0.5 acres",
    parkingSpaces: 4,
    propertyType: "Villa",
    reference: "SL-SPV-102",
    description: "A private sanctuary on half an acre in Spring Valley. Master suite with private sauna, bespoke timber millwork, and heated lap pool.",
    amenities: ["Private Sauna", "Lap Pool", "Fireplace", "CCTV & Alarm System", "Gazebo"],
    yearBuilt: 2022,
    images: [
      { url: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80", alt: "Front Elevation" },
    ],
  },
  {
    id: "prop-vil-03",
    slug: "4-bedroom-townhouse-runda",
    title: "4 Bedroom Gated Community Townhouse, Runda",
    location: "Runda, Nairobi",
    status: "available",
    isFeatured: false,
    category: "villas",
    listingType: "for-rent",
    priceKes: 280000,
    priceSuffix: "/ mo",
    imageUrl: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80",
    imageAlt: "Gated Community Townhouse in Runda",
    bedrooms: 4,
    bathrooms: 4,
    area: "320 m²",
    parkingSpaces: 3,
    propertyType: "Townhouse",
    reference: "SL-RUN-103",
    description: "Immaculate townhouse in UN-approved security zone. UN blue-badge ready, clubhouse facilities, and expansive family room.",
    amenities: ["UN Approved Security", "Clubhouse", "Tennis Court", "Compound Backup Power"],
    yearBuilt: 2021,
    images: [
      { url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80", alt: "Living Area" },
    ],
  },
  {
    id: "prop-vil-04",
    slug: "5-bedroom-colonial-estate-muthaiga",
    title: "5 Bedroom Grand Estate, Muthaiga",
    location: "Muthaiga, Nairobi",
    status: "available",
    isFeatured: true,
    category: "villas",
    listingType: "for-sale",
    priceKes: 240000000,
    priceSuffix: null,
    imageUrl: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80",
    imageAlt: "Grand Estate in Muthaiga",
    bedrooms: 5,
    bathrooms: 6,
    area: "1.2 acres",
    parkingSpaces: 8,
    propertyType: "Residential",
    reference: "SL-MUT-104",
    description: "Palatial 1.2 acre residence in Nairobi's most prestigious diplomatic enclave. Expansive lawns, tennis court, and security guardhouse.",
    amenities: ["Tennis Court", "Guardhouse", "Guest Cottage", "Borehole", "Wine Cellar"],
    yearBuilt: 2019,
    images: [
      { url: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80", alt: "Estate Grounds" },
    ],
  },
  {
    id: "prop-vil-05",
    slug: "beachfront-4-bedroom-villa-nyali",
    title: "Beachfront 4 Bedroom Coastal Haven, Nyali",
    location: "Nyali, Mombasa",
    status: "let",
    isFeatured: false,
    category: "villas",
    listingType: "for-rent",
    priceKes: 220000,
    priceSuffix: "/ mo",
    imageUrl: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1200&q=80",
    imageAlt: "Beachfront Villa in Nyali",
    bedrooms: 4,
    bathrooms: 4,
    area: "0.5 acres",
    parkingSpaces: 4,
    propertyType: "Villa",
    reference: "SL-NYA-105",
    description: "Direct oceanfront living with private beach access, Swahili-inspired architecture, and sea-breeze courtyards.",
    amenities: ["Private Beach Access", "Swimming Pool", "Swahili Architecture", "Backup Generator"],
    yearBuilt: 2020,
    images: [
      { url: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1200&q=80", alt: "Beachfront Pool" },
    ],
  },

  // ── Commercial ──
  {
    id: "prop-com-01",
    slug: "grade-a-office-suite-upper-hill",
    title: "Grade A Office Floor Plate, Upper Hill",
    location: "Upper Hill, Nairobi",
    status: "available",
    isFeatured: true,
    category: "commercial",
    listingType: "for-rent",
    priceKes: 380000,
    priceSuffix: "/ mo",
    imageUrl: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1200&q=80",
    imageAlt: "Grade A Office in Upper Hill",
    bedrooms: null,
    bathrooms: 4,
    area: "2,800 sqft",
    parkingSpaces: 6,
    propertyType: "Office",
    reference: "SL-UPH-201",
    description: "Fitted modern office floor in a premier financial district tower. Fiber optic infrastructure, central HVAC, and access-controlled entry.",
    amenities: ["Central HVAC", "Fiber Optic Connectivity", "Access Control", "High Speed Lifts", "Visitor Parking"],
    yearBuilt: 2022,
    images: [
      { url: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1200&q=80", alt: "Office Suite" },
    ],
  },
  {
    id: "prop-com-02",
    slug: "commercial-headquarters-westlands",
    title: "Standalone Commercial Headquarters, Westlands",
    location: "Westlands, Nairobi",
    status: "available",
    isFeatured: false,
    category: "commercial",
    listingType: "for-sale",
    priceKes: 320000000,
    priceSuffix: null,
    imageUrl: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80",
    imageAlt: "Commercial Headquarters in Westlands",
    bedrooms: null,
    bathrooms: 8,
    area: "12,000 sqft",
    parkingSpaces: 25,
    propertyType: "Commercial",
    reference: "SL-WST-202",
    description: "Four-level standalone commercial building suitable for corporate headquarters, medical center, or regional diplomatic office.",
    amenities: ["Dedicated Substation", "Ample Basement Parking", "Rooftop Terrace", "Guard House"],
    yearBuilt: 2021,
    images: [
      { url: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80", alt: "Exterior Tower" },
    ],
  },
  {
    id: "prop-com-03",
    slug: "logistics-warehouse-tatu-city",
    title: "Modern Logistics Godown & Warehouse, Tatu City",
    location: "Tatu City, Kiambu",
    status: "under_offer",
    isFeatured: false,
    category: "commercial",
    listingType: "for-rent",
    priceKes: 520000,
    priceSuffix: "/ mo",
    imageUrl: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=1200&q=80",
    imageAlt: "Warehouse in Tatu City",
    bedrooms: null,
    bathrooms: 2,
    area: "8,500 sqft",
    parkingSpaces: 8,
    propertyType: "Industrial",
    reference: "SL-TAT-203",
    description: "High-spec industrial warehouse inside Tatu Industrial Park. 9m clear eaves height, heavy vehicle turning radius, and three-phase power.",
    amenities: ["Three Phase Power", "9m Eaves Height", "Heavy Vehicle Access", "SEZ Benefits"],
    yearBuilt: 2023,
    images: [
      { url: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=1200&q=80", alt: "Warehouse" },
    ],
  },

  // ── Land & Plots ──
  {
    id: "prop-lnd-01",
    slug: "prime-half-acre-residential-plot-karen",
    title: "Prime 0.5 Acre Residential Plot, Karen",
    location: "Karen, Nairobi",
    status: "available",
    isFeatured: true,
    category: "land",
    listingType: "for-sale",
    priceKes: 38000000,
    priceSuffix: null,
    imageUrl: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80",
    imageAlt: "Residential Plot in Karen",
    bedrooms: null,
    bathrooms: null,
    area: "0.5 acres",
    parkingSpaces: null,
    propertyType: "Land",
    reference: "SL-KAR-301",
    description: "Gently sloping half-acre parcel with red soil, mature indigenous trees, and clean freehold title deed. Gated private road access.",
    amenities: ["Red Soil", "Electricity On Site", "Council Water Connected", "Freehold Title Deed"],
    yearBuilt: null,
    images: [
      { url: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80", alt: "Land Parcel" },
    ],
  },
  {
    id: "prop-lnd-02",
    slug: "prime-1-acre-redevelopment-riverside",
    title: "Prime 1 Acre Redevelopment Land, Riverside Drive",
    location: "Riverside Drive, Nairobi",
    status: "available",
    isFeatured: true,
    category: "land",
    listingType: "for-sale",
    priceKes: 260000000,
    priceSuffix: null,
    imageUrl: "https://images.unsplash.com/photo-1513836279014-a89f7a76ae86?auto=format&fit=crop&w=1200&q=80",
    imageAlt: "Land on Riverside Drive",
    bedrooms: null,
    bathrooms: null,
    area: "1.0 acre",
    parkingSpaces: null,
    propertyType: "Land",
    reference: "SL-RIV-302",
    description: "High-density zoning commercial/residential 1-acre plot along Riverside Drive. Excellent road frontage and sewer connection ready.",
    amenities: ["Commercial/Residential Zoning", "Dual Road Frontage", "Sewer Connection", "Clean Title"],
    yearBuilt: null,
    images: [
      { url: "https://images.unsplash.com/photo-1513836279014-a89f7a76ae86?auto=format&fit=crop&w=1200&q=80", alt: "Riverside Land" },
    ],
  },
  {
    id: "prop-lnd-03",
    slug: "2-5-acres-commercial-parcel-gigiri",
    title: "2.5 Acres Commercial Parcel, Gigiri",
    location: "Gigiri, Nairobi",
    status: "available",
    isFeatured: false,
    category: "land",
    listingType: "for-sale",
    priceKes: 450000000,
    priceSuffix: null,
    imageUrl: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80",
    imageAlt: "Commercial Parcel in Gigiri",
    bedrooms: null,
    bathrooms: null,
    area: "2.5 acres",
    parkingSpaces: null,
    propertyType: "Land",
    reference: "SL-GIG-303",
    description: "Rare 2.5 acre land parcel located adjacent to diplomatic missions and major UN agencies. Fully serviced and ready for institutional development.",
    amenities: ["Diplomatic Security Zone", "Three Phase Power", "Wide Frontage", "Paved Access"],
    yearBuilt: null,
    images: [
      { url: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80", alt: "Gigiri Land" },
    ],
  },
];
